set -g prefix C-t
unbind-key C-b
bind-key C-t send-prefix

set -g default-terminal xterm-256color

set-option -g default-shell /bin/zsh

# powerline
set-option -g pane-active-border-style fg="colour${COLOR_DARK}"
set-option -g pane-active-border-style bg="black"
set-window-option -g pane-border-style bg="black"
set-window-option -g pane-border-style fg="colour${COLOR_DARK}"
set-window-option -g window-status-current-style fg="colour${COLOR_DARK}"

set -g status on
# set -g status-utf8 on # no longer necesssary
set -g status-interval 2
set -g status-fg colour231
set -g status-bg colour234
set -g status-left-length 20
set -g status-left "#[fg=colour${COLOR_DARK},bg=colour231,bold] #S #(powerline tmux left)"
set -g status-right ''
set -g status-right-length 150
set -g window-status-format "#[fg=colour244,bg=colour234] #I #[fg=colour249]#W "
set -g window-status-current-format "#[fg=colour231,bg=colour${COLOR_DARK}] #I #[fg=colour231,bold]#W "
set -g history-limit 100000

set -g mouse on

unbind -T copy-mode-vi WheelUpPane
unbind -T copy-mode-vi WheelDownPane
unbind -T copy-mode WheelUpPane
unbind -T copy-mode WheelDownPane

bind -T copy-mode-vi WheelUpPane   select-pane -t= \; send-keys -X -N 1 scroll-up
bind -T copy-mode-vi WheelDownPane select-pane -t= \; send-keys -X -N 1 scroll-down
bind -T copy-mode    WheelUpPane   select-pane -t= \; send-keys -X -N 1 scroll-up
bind -T copy-mode    WheelDownPane select-pane -t= \; send-keys -X -N 1 scroll-down


# https://kurochan-note.hatenablog.jp/entry/2026/02/03/074837
bind -n S-Enter send-keys Escape "[13;2u"
